version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /apps/client_flutter
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /apps/partner_flutter
    schedule:
      interval: weekly
